# Generated by Django 2.0.7 on 2018-07-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('stupid', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('dump', models.IntegerField()),
            ],
        ),
    ]
